services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./back/db:/usr/src/app/back/db
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
