/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    BuyItemIcon: typeof import('./src/components/BuyItemIcon.vue')['default']
    CatanEdgeOverlay: typeof import('./src/components/CatanEdgeOverlay.vue')['default']
    CatanGameView: typeof import('./src/components/CatanGameView.vue')['default']
    CatanHarbourComponent: typeof import('./src/components/CatanHarbourComponent.vue')['default']
    CatanHexGrid: typeof import('./src/components/CatanHexGrid.vue')['default']
    CatanIntersectionComponent: typeof import('./src/components/CatanIntersectionComponent.vue')['default']
    CatanPlayerCards: typeof import('./src/components/CatanPlayerCards.vue')['default']
    CatanResourceCountSelector: typeof import('./src/components/CatanResourceCountSelector.vue')['default']
    CatanResourceTypeSelector: typeof import('./src/components/CatanResourceTypeSelector.vue')['default']
    CatanRoadComponent: typeof import('./src/components/CatanRoadComponent.vue')['default']
    CatanSettings: typeof import('./src/components/CatanSettings.vue')['default']
    CatanTerrainHexComponent: typeof import('./src/components/CatanTerrainHexComponent.vue')['default']
    CatanTradeDialog: typeof import('./src/components/CatanTradeDialog.vue')['default']
    CatanVertexOverlay: typeof import('./src/components/CatanVertexOverlay.vue')['default']
    City: typeof import('./src/components/City.vue')['default']
    DevelopmentCardDialog: typeof import('./src/components/DevelopmentCardDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dice: typeof import('./src/components/Dice.vue')['default']
    PlayerTradeOfferDialog: typeof import('./src/components/PlayerTradeOfferDialog.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Settlement: typeof import('./src/components/Settlement.vue')['default']
    TradeOfferAnswerDialog: typeof import('./src/components/TradeOfferAnswerDialog.vue')['default']
  }
}
